<!-- ## numpy tricks -->

In [41]:
import numpy as np

In [42]:
a = np.random.randint(1,100,15)
a

array([36, 28,  1, 82, 99, 87, 64, 40, 16, 55, 33, 76, 17, 87, 81],
      dtype=int32)

In [43]:
b = np.random.randint(1 ,100 , 16).reshape(4,4)
b

array([[72, 42, 73, 57],
       [93, 38, 88, 44],
       [91, 80,  8,  8],
       [88, 98,  5, 17]], dtype=int32)

In [ ]:
# sorting method in numpy 
# [::-1] is used to print in descending order
np.sort(a)[::-1]

array([83, 81, 79, 72, 72, 61, 57, 49, 45, 42, 29, 27, 12,  9,  3],
      dtype=int32)

In [ ]:
# on 2d array 
# axis is used to define row or column
# 0 = column ; 1 = row
np.sort(b,axis=0)

array([[19, 14, 39, 13],
       [29, 71, 45, 31],
       [32, 81, 54, 36],
       [76, 82, 56, 55]], dtype=int32)

In [ ]:
# append is used to enter a new element at the last of the numpy array 

np.append(a,200)

array([ 79,  81,  72,  61,  72,  45,  12,  27,   9,  57,  49,   3,  42,
        83,  29, 200])

In [ ]:
np.append(b,np.random.random((b.shape[0],1)),axis=1)

array([[19.        , 82.        , 45.        , 13.        ,  0.98204386],
       [32.        , 81.        , 56.        , 31.        ,  0.12042947],
       [29.        , 71.        , 39.        , 55.        ,  0.1618885 ],
       [76.        , 14.        , 54.        , 36.        ,  0.78987063]])

In [ ]:
# np.concatenate is used to add two array 
# we can provide axis which define where to add the array
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)

print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [ ]:
np.concatenate((c,d) , axis=1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

In [ ]:
# np.unique

# With the help of np.unique() method, we can get the unique values from an array given as parameter in np.unique() method.

e = np.array([1,1,2,2,3,3,4,4,5,5,6,6])

np.unique(e)

array([1, 2, 3, 4, 5, 6])

In [ ]:
# np.expand_dims

# With the help of Numpy.expand_dims() method, we can get the expanded dimensions of an array

a.shape

np.expand_dims(a, axis=1).shape

(15, 1)

In [ ]:
# np.where

# The numpy.where() function returns the indices of elements in an input array where the given condition is satisfied.

a
# np.where(condition , true , false)
np.where(a % 2 == 0 , 0 , a)

array([79, 81,  0, 61,  0, 45,  0, 27,  9, 57, 49,  3,  0, 83, 29],
      dtype=int32)

In [ ]:
# np.argmax

# The numpy.argmax() function returns indices of the max element of the array in a particular axis.

# in 1d array
a
np.argmax(a)

# in 2d array 
print(b)
np.argmax(b , axis=0)

[[19 82 45 13]
 [32 81 56 31]
 [29 71 39 55]
 [76 14 54 36]]


array([3, 0, 1, 2])

In [ ]:
# np.argmin -> just opposite of argmax

np.argmin(a)

np.int64(11)

In [ ]:
# np.cumsum

# numpy.cumsum() function is used when we want to compute the cumulative sum of array elements over a given axis.

a
np.cumsum(a)

array([ 79, 160, 232, 293, 365, 410, 422, 449, 458, 515, 564, 567, 609,
       692, 721])

In [ ]:
np.cumsum(b, axis=0)

array([[ 19,  82,  45,  13],
       [ 51, 163, 101,  44],
       [ 80, 234, 140,  99],
       [156, 248, 194, 135]])

In [44]:
# We have commulative product too 
np.cumprod(a)

array([                  36,                 1008,                 1008,
                      82656,              8182944,            711916128,
                45562632192,        1822505287680,       29160084602880,
           1603804653158400,    52925553554227200,  4022342070121267200,
       -5407161102776664064,  9192329974878568448,  6708965016781979648])

In [45]:
# np.percentile

# numpy.percentile()function used to compute the nth percentile of the given data (array elements) along the specified axis.

a 

np.percentile(a , 50)
np.percentile(b , 50)


np.float64(64.5)

In [49]:
# np.histogram
# Numpy has a built-in numpy.histogram() function which represents the frequency of data distribution in the graphical form.

a

np.histogram(a,bins=[0,50,100])

(array([7, 8]), array([  0,  50, 100]))

In [50]:
# np.corrcoef
# Return Pearson product-moment correlation coefficients

salary = np.array([20000,40000,25000,35000,60000])
experience = np.array([1,3,2,4,2])

np.corrcoef(salary,experience)

array([[1.        , 0.25344572],
       [0.25344572, 1.        ]])

### np.isin

With the help of numpy.isin() method, we can see that one array having values are checked in a different numpy array having different elements with different sizes.

In [51]:
items = [10,20,30,40,50,60,70,80,90,100]

a[np.isin(a,items)]

array([40], dtype=int32)

In [ ]:
# np.flip

# The numpy.flip() function reverses the order of array elements along the specified axis, preserving the shape of the array.

np.flip(a)

array([81, 87, 17, 76, 33, 55, 16, 40, 64, 87, 99, 82,  1, 28, 36],
      dtype=int32)

In [55]:
# np.put

# The numpy.put() function replaces specific elements of an array with given values of p_array. Array indexed works on flattened array.


np.put(a,[0,1],[110,530])
a

array([110, 530,   1,  82,  99,  87,  64,  40,  16,  55,  33,  76,  17,
        87,  81], dtype=int32)

In [ ]:
# np.delete

# The numpy.delete() function returns a new array with the deletion of sub-arrays along with the mentioned axis.

# np.delete(array_name , index)
np.delete(a,[0,2,4])

### Set functions

- np.union1d
- np.intersect1d
- np.setdiff1d
- np.setxor1d
- np.in1d

In [57]:
# union -> np.union1d() function, which returns the sorted union of two arrays, meaning it combines both arrays, removes duplicates, and sorts the result.

m = np.array([1,2,3,4,5])
n = np.array([3,4,5,6,7])

np.union1d(m,n)

array([1, 2, 3, 4, 5, 6, 7])

In [58]:
# intersection -> Returns the sorted intersection of two arrays — only elements that appear in both arrays.
 
np.intersect1d(m,n)

array([3, 4, 5])

In [59]:
np.setdiff1d(n,m)

array([6, 7])

In [60]:
np.setxor1d(m,n)

array([1, 2, 6, 7])

In [ ]:
# m[np.in1d(m,1)]

C:\Users\ieish\AppData\Local\Temp\ipykernel_14376\524887286.py:1: DeprecationWarning: `in1d` is deprecated. Use `np.isin` instead.
  m[np.in1d(m,1)]


array([1])