## Import numpy as np and see the version


In [1]:
import numpy as np

print(np.__version__)

2.3.2


### How to create a 1D array?

In [2]:
a = np.array([1 , 3 , 4 ,5 ])

print(a)

[1 3 4 5]


### How to create a boolean array?

In [6]:
a = np.full((3,3), True, dtype=bool)
print(a)

b = np.full(9, True, dtype=bool).reshape((3,3))
print(b)

c = np.ones((3,3) , dtype=bool)
print(c)

d = np.identity((3) , dtype=bool)
print(d)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
[[ True False False]
 [False  True False]
 [False False  True]]


### How to extract items that satisfy a given condition from 1D array?

In [13]:
a = np.arange(10).reshape(5,2)

print(a)

arr1 = a[a % 2==0]
print(arr1)

arr1 = a+2
print(arr1)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
[0 2 4 6 8]
[[ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]]
